apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: my-gateway-routes
spec:
  routes:
  # - uri: https://httpbin.org
  #   predicates:
  #     - Path=/demo/**
  #     - Host=**.example.com
  #     - Weight=group1, 5
  #   filters:
  #     - SetPath=/uuid
  - uri: https://httpbin.org
    predicates:
      - Path=/demo/{delay}
      - Host=**.example.com
    filters:
      - SetPath=/drip
      - AddResponseHeader=tanzu,responseheader
      - AddRequestParameter=duration, 0 # time to drip each byte (seconds)
      - AddRequestParameter=numbytes, 10
      - AddRequestParameter=code, 200   # response code
      - AddRequestParameter=delay, {delay}  # delay before responding (seconds)
      - CircuitBreaker=myCircuitBreaker:4s

      # A list of status codes that will trigger the fallback behaviour, this can be expressed in number and text format separated by a colon.
      # The failure rate threshold above which the circuit breaker will be opened (default 50%, expressed as float value).
      # Duration of wait time before closing again (default 60s).

      # time http :8080/demo/5 Host:example.com