apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: my-gateway-routes
spec:
  routes:
  - uri: https://httpbin.org
    predicates:
      - Path=/trial
    filters:
      - SetPath=/uuid
      - AddResponseHeader=tanzu,responseheader
      - CircuitBreaker=myCircuitBreaker,forward:/httpbin.org,401:NOT_FOUND:500
