apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-custom-ingress
  namespace: custom-scg
spec:
  ingressClassName: contour
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: custom-my-gateway
            port:
              number: 80